### ISSUE TITLE
Crash when tapping send or receive (Lightning)

### ISSUE THREAD

**Issue by jlopp** [ZeusLN/zeus#1113]
### Describe the bug

As of today every time I try to send or receive a lightning payment on GraphenOS, the app instantly crashes. This is odd because it worked fine for me last week and I haven't changed app versions since then.

### Reproduce

Not sure what conditions are at play, it crashes for me every time now.

### Zeus version

v0.6.0

### Network

Clearnet

### Device

Pixel 3

### Device operating system

GrapheneOS

### Log output

```shell
type: crash
osVersion: google/sargo/sargo:12/SP2A.220505.008/2022090700:user/release-keys
package: app.zeusln.zeus:30
process: app.zeusln.zeus

com.facebook.react.common.d: TypeError: Q.filter is not a function

This error is located at:
    in f
    in RCTView
    in View
    in MobXProvider
    in o
    in RCTView
    in View
    in RCTView
    in View
    in h, js engine: v8, stack:
n.value@1518:4515
i._allowStateChanges@436:159
<unknown>@434:6619
ye@436:17039
e.track@436:29975
n.b [as render]@434:6572
n.<anonymous>@434:6713
n.T.t.render.t.isReactClass.Object.isPrototypeOf.call.n.render@434:6725
qr@92:50433
Yr@92:50228

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:103)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:149)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:920)
```

**Comment by jlopp** [comment]
After upgrading to the latest version of Zeus I'm no longer experiencing this error.
