### ISSUE TITLE
Crash when click on first node in closed channels list

### ISSUE THREAD

**Issue by kirkawolff** [ZeusLN/zeus#1378]
### Describe the bug

This is reproducible on my system, but it may only happen with the particular node I'm clicking on.

### Reproduce

Zeus is configured with LND over a local 10.x internal network.
Steps:
1. Open  Zeus
2. Unlock with biometrics
3. Click on rightmost button in bottom for list of LN channels
4. Click on "Channels" title to switch to pending channels screen
5. Click on "Pending Channels" title to switch to closed channels screen
6. Click on first closed channel "Lightning is the way"
7. App crashes

### Zeus version

v0.7.3

### Node interface

LND (REST)

### Network

Clearnet

### Device

Pixel 6 pro

### Device operating system

Android 13 GrapheneOS build TQ1A.230205.002.2023030400

### Log output

```shell
type: crash
osVersion: google/raven/raven:13/TQ1A.230205.002/2023030400:user/release-keys
package: app.zeusln.zeus:62
process: app.zeusln.zeus
processUptime: 9991 + 202 ms

h6.c: Error: Text strings must be rendered within a <Text> component.

This error is located at:
    in NavigationContainer
    in RCTView
    in Unknown
    in Observer
    in AppContainer
    in MobXProvider
    in App
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes, stack:
completeWork@1:121168
completeUnitOfWork@1:134413
performUnitOfWork@1:134258
workLoopSync@1:134125
renderRootSync@1:134009
performSyncWorkOnRoot@1:131501
flushSyncCallbacks@1:96762
batchedUpdatesImpl@1:147879
batchedUpdates@1:89633
_receiveRootNodeIDEvent@1:89906
receiveTouches@1:142771
__callFunction@1:162154
anonymous@1:160702
__guard@1:161642
callFunctionReturnFlushedQueue@1:160660

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:75)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:148)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:147)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:1012)

```
```

**Comment by kaloudis** [comment]
@kirkawolff any difference in v0.7.4?

**Comment by kirkawolff** [comment]
Yes it is different, it doesn't crash anymore but it does rewrite all of the "pending close channels" that are pending (and no longer in the mempool) into the first of the list and the indices of the items refer to other channels of the same on lnd name regardless if they are open or closed
