### ISSUE TITLE
App crashes after deleting last node

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1487]
### Describe the bug

After deleting the last node, the Zeus splash screen is endlessly shown.

Additionally, when deleting the currently active node, another node becomes active automatically. This might not be wanted so it would be better to let the user select a new node.

### Reproduce

- Have only one node configured
- Delete the node

### Zeus version

v0.7.6

### Node interface

LND (REST)

### Network

Clearnet

### Device

Android Emulator Pixel 6 Pro

### Device operating system

Android 13

### Log output

```shell
ERROR  TypeError: Cannot read property 'implementation' of undefined

This error is located at:
    in NavigationContainer (created by App)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by LinearGradient)
    in LinearGradient (created by Screen)
    in Screen (created by Observer)
    in Observer (created by AppContainer)
    in AppContainer (created by App)
    in MobXProvider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in zeus(RootComponent), js engine: hermes
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'implementation' of undefined
TypeError: Cannot read property 'implementation' of undefined
    at BlueWalletWarning (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:272632:26)
    at renderWithHooks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:7772:33)
    at mountIndeterminateComponent (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:10311:34)
    at beginWork (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:11209:49)
    at beginWork$1 (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:14596:29)
    at performUnitOfWork (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:14112:29)
    at workLoopSync (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:14060:28)
    at renderRootSync (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:14042:25)
    at performSyncWorkOnRoot (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:13832:40)
    at flushSyncCallbacks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:5240:36)
    at flushSyncCallbacksOnlyInLegacyMode (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:5225:29)
    at batchedUpdates$1 (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:13866:47)
    at batchedUpdates (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:3235:36)
    at reactionScheduler (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:103805:16)
    at runReactions (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:103783:22)
    at endBatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:103543:19)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:102559:15)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:103227:25)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:105693:31)
    at set (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:105859:26)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:176529:27)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:20549:26)
    at _next (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:20568:29)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/3f4v354d/x86_64/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/3f4v354d/x86_64/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:26121:26)
    at _callTimer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:26040:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:26070:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:26233:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:19686:46)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:19498:45)
    at __guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:19670:15)
    at flushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:19497:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=app.zeusln.zeus&modulesOnly=false&runModule=true:19491:33)
```

**Comment by kaloudis** [comment]
When deleting a node, if it is currently the active node, and if there are other nodes available, the first node in the list should become the active node, but the user should be returned to the node list to change their selection if they so choose

**Comment by myxmaster** [comment]
I personally would'nt want Zeus to connect to the next first node in the list, just because I deleted the currently active node. It might be that I have multiple other connection configs and maybe its the last one in the list I want to connect to now...? And even if only 1 last node config is left after deletion, maybe I want to configure a new one instead of connecting an existing config.

But no big deal, if you like it better that way, no problem :)
