### ISSUE TITLE
OutOfMemoryError when loading activity

### ISSUE THREAD

**Issue by ShatteredBunny** [ZeusLN/zeus#2465]
When loading the activity of an LND node Zeus crashes due to an out of memory error.
There are lots of rebalancing tx in the history, although they are older than a year and I think the history used to work.
The log does not seem to have much information, please let me know if I can help with further information

```
app.zeusln.zeus E AndroidRuntime : FATAL EXCEPTION: qg.a0 Dispatcher
Process: app.zeusln.zeus, PID: 24712
java.lang.OutOfMemoryError: Failed to allocate a 290011288 byte allocation with 33554432 free bytes and 263MB until OOM, target footprint 294578952, growth limit 536870912
	at java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:87)
	at java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:71)
	at java.nio.CharBuffer.allocate(CharBuffer.java:380)
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:858)
	at com.ReactNativeBlobUtil.g.g(Unknown Source:326)
	at com.ReactNativeBlobUtil.g.c(Unknown Source:0)
	at com.ReactNativeBlobUtil.g$e.a(Unknown Source:114)
	at vg.e$a.run(Unknown Source:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by kaloudis** [comment]
Could you provide your phone model?

**Comment by JaviLib** [comment]
This could be related to my issue. In my case, it never loads the activity:

![Image](https://github.com/user-attachments/assets/94a827bf-d737-4283-9c86-f193138966a3)

This is the IOS version running on a mac (under emulation).

I have thousands of tx in my past activity of my node, and I am using lndrest to connect to it.

As described in the group: https://t.me/zeusLN/88979

Coming from #1328

**Comment by ShatteredBunny** [comment]
The limits while fetching tx did the trick, no crashes anymore and lnd is able to handle the requests quite fast
