### ISSUE TITLE
v0.6.0-rc1 no longer works with lnbits (using the lndhub extension)

### ISSUE THREAD

**Issue by djkazic** [ZeusLN/zeus#774]
**Describe the bug**
On previous versions, scanning the lnbits lndhub QR code resulted in a working wallet -- loading balances and history.

**To Reproduce**
1. Load up lnbits wallet page, go to extensions to bring up the pairing QR code
2. Scan the QR code into Zeus wallet and wait for it to finish adding it
3. Select the newly added account as active and try to load the balances

**Expected behavior**
Balances and history load when you visit each respective page

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 5A
 - OS: Android 12
 - Zeus Version: v0.6.0-rc1
 - Clearnet

**Additional context**
N/A

**Comment by kaloudis** [comment]
Are you using the legend or infinity server?

**Comment by djkazic** [comment]
Legend

**Comment by kaloudis** [comment]
Oh, I see what's happening. The nodes list isn't updating after scan. Please confirm, but if you back out to the main view and go back to Settings > Nodes it'll show up. Will have a fix in rc2 tomorrow.

**Comment by djkazic** [comment]
No, I can see the node and select it normally. However it loads infinitely and just shows 0 sats for the balance.

**Comment by djkazic** [comment]
![Screenshot_20220206-220300](https://user-images.githubusercontent.com/3331929/152717947-83f7a268-674c-42fc-b70a-c36631ce1dd4.png)

**Comment by kaloudis** [comment]
Hmm. Can't recreate. Seems to work for me.

**Comment by kaloudis** [comment]
@djkazic could you check to see if it still works for you in an older build?

**Comment by kaloudis** [comment]
try `v0.6.0-beta2` please

**Comment by djkazic** [comment]
I see the same behavior on that version as well

**Comment by kaloudis** [comment]
Any chance you could try another network? Maybe you have a VPN or firewall blocking your calls.

**Comment by djkazic** [comment]
Tried it both with and without Mullvad. This is my home lnbits instance so everything is going from external network -> NAT -> nginx -> lnbits. I've tested the same lndhub endpoint with BlueWallet and it is functioning normally there.

Let me know if you would like to test my lnbits instance. I can DM you the URL.

**Comment by kaloudis** [comment]
I'll take a stab at it. Please send me the link.

**Comment by djkazic** [comment]
https://lnbits.eldamar.icu

**Comment by kaloudis** [comment]
It's because of your certificate on your server I believe. I think the chain isn't tied to an authority properly.

**Comment by djkazic** [comment]
Hmm, OK. I'll check out my letsencrypt and nginx config.

**Comment by djkazic** [comment]
OK, so I have the fullchain.pem being pointed to; I think this contains the two certs that correspond to the chain of trust.
![image](https://user-images.githubusercontent.com/3331929/152834296-811629c7-035e-4cd2-bdb2-6b716c507a36.png)
![image](https://user-images.githubusercontent.com/3331929/152834246-6f818dd8-2d13-46fb-b5a3-a7bbcffcbea4.png)

Is there anything I'm missing?

**Comment by djkazic** [comment]
It's also worth noting I tried importing the wallet with cert verification off. Would this in theory work, or would the certs problem still cause the loading to fail?

**Comment by djkazic** [comment]
I've turned off CloudFlare proxying but the issue persists. I'm wondering if this is because the ISRG CA certs I have are out of date on the client device.

**Comment by djkazic** [comment]
My lnbits backend complains with this error:
```handled error Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/quart_trio/app.py", line 151, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/opt/venv/lib/python3.7/site-packages/quart/app.py", line 1933, in dispatch_request
    return await handler(**request_.view_args)
  File "/app/lnbits/extensions/lndhub/decorators.py", line 12, in wrapped_view
    token = request.headers["Authorization"].split("Bearer ")[1]
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/datastructures.py", line 977, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.```

**Comment by djkazic** [comment]
And from nginx:
```192.168.1.1 - - [07/Feb/2022:17:41:37 +0000] "POST /lndhub/ext/auth?type=auth HTTP/1.1" 200 152 "-" "okhttp/3.12.1"
192.168.1.1 - - [07/Feb/2022:17:41:37 +0000] "GET /lndhub/ext/balance HTTP/1.1" 500 865 "-" "okhttp/3.12.1"
192.168.1.1 - - [07/Feb/2022:17:41:37 +0000] "POST /lndhub/ext/auth?type=auth HTTP/1.1" 200 152 "-" "okhttp/3.12.1"
192.168.1.1 - - [07/Feb/2022:17:41:37 +0000] "GET /lndhub/ext/balance HTTP/1.1" 500 865 "-" "okhttp/3.12.1"```

**Comment by djkazic** [comment]
I installed an older version (v0.6.0-beta1) and the wallet works

**Comment by kaloudis** [comment]
Looks like you're missing your root chain http://www.sslchecker.com/sslchecker?su=f828f2a090bf7ed93d3118f6126130b5

**Comment by djkazic** [comment]
OK, so I'm behind cloudflare routing. I can't add the root cert to be returned since the requests are proxied. Any way I can work around this?

**Comment by kaloudis** [comment]
@djkazic have you tried installing the server ssl certificate to your phone?

**Comment by kaloudis** [comment]
Closing for inactivity
