### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [ZeusLN/zeus#910]
```
:ReactNative:Running '[node, -e, console.log(require('react-native/cli').bin);]' command failed.

FAILURE: Build failed with an exception.

* Where:
Script '/home/vagrant/build/app.zeusln.zeus/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 213

* What went wrong:
A problem occurred evaluating script.
> /home/vagrant/build/app.zeusln.zeus/node_modules/@react-native-community/cli/build/commands/doctor/healthchecks/index.js:48  } catch {}          ^SyntaxError: Unexpected token {    at createScript (vm.js:80:10)    at Object.runInThisContext (vm.js:139:10)    at Module._compile (module.js:616:28)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Module.require (module.js:596:17)    at require (internal/module.js:11:18)    at Object.<anonymous> (/home/vagrant/build/app.zeusln.zeus/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:28:21)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Could you please take a look? Thanks!

**Comment by kaloudis** [comment]
@linsui we are no longer maintaining the default F-Droid build. We have moved to a self-hosted F-Droid repo using reproducible builds

**Comment by linsui** [comment]
Should we archive it then?

**Comment by kaloudis** [comment]
Yes, please.

**Comment by linsui** [comment]
Done. :ok_hand:

**Comment by kaloudis** [comment]
To anyone following along, our self-hosted F-Droid repo details can be found on our download page: https://zeusln.app/download

**Comment by licaon-kter** [comment]
So this is reproducible only with Google proprietary libs inside?

**Comment by kaloudis** [comment]
I don't think we've added any proprietary libs - just haven't been able to maintain the F-Droid config. We use Docker for our new build system.

**Comment by licaon-kter** [comment]
One of your deps does, I meant: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/app.zeusln.zeus.yml#L256-L258
